### ISSUE TITLE
Sets of results with all divisions rowing over

### ISSUE THREAD

**Issue by mcshane-fire** [mcshane-fire/bumps#2]
There are results with all divisions rowing over.  It's possible this is an error in the results file, which needs to be fixed. 

Some are divisions not raced, which should be replaced with a t code to indicate this properly.

**Comment by mcshane-fire** [comment]
Checking for divisions of at least 8 crews all rowing over:
`grep -E "(^| )rrrrrrrr+( |$)" *`

[row_overs.txt](https://github.com/mcshane-fire/bumps/files/12339549/row_overs.txt)

**Comment by mcshane-fire** [comment]
Example here is Torpids 1984 Women.  ad_format results file has all crews rowing over each day
https://github.com/johnwalley/bumps-results/blob/master/results/ad_format/t1984w.txt
Per-crew data has three crews missing (St Hugh's 3, St Hugh's 4, St Hilda's 3) but adding those enables the per-crew files to generate the correct results.  I've done that, generated those results and committed them as ed3d1aad9fb41de63b2e0b48438d5e21d5ae0ef7.  I'm unsure whether there is a better way.

@johnwalley  - can you look into why the ad_format results data seems wrong?  I don't know if this can be regenerated somehow correctly, or whether we need to add in missing crew information for all crews we don't have per-crew data from (~1k crews).  Looking at https://eodg.atm.ox.ac.uk/user/dudhia/rowing/bumps/shug/index.html there is no mention of a Torpids Women's 3rd or 4th boat, so don't know how to get hold of this data other than manually adding it by looking at the bumps chart and adding lines to the escapes.py file.

**Comment by johnwalley** [comment]
For the Torpids 1984 women's result there is a correct set of results available from Anu so I wonder if it as been updated in the intervening 5 years since I last looked. I'll update it in my repo and do the same for the other possible erroneous results files. I'll let you know when it's done.

**Comment by johnwalley** [comment]
I've gone through the Torpids results with full division row overs. I found the following incorrect files:

t1977m.txt (should not have been present, was a duplicate of t1976m.txt, looks like no racing tool place that year)
t1978w.txt (updated with current results from Anu Dudhia)
t1984w.txt (updated with current results from Anu Dudhia)

The rest looked correct in the sense that they match up with the results files at https://eodg.atm.ox.ac.uk/user/dudhia/rowing/bumps.

I've updated my repo with these two commits:

https://github.com/johnwalley/bumps-results/commit/0fac157fba65c0aa376b333177e580b885d3b2ae
https://github.com/johnwalley/bumps-results/commit/96b0f4b6d97ac23c055cce04a86d00c79ac88dc4

I'll do the same for CRA, Lents, and Eights.

**Comment by mcshane-fire** [comment]
From the latest results of that grep:

CRA 1964: Matches https://cantabsrowing.org.uk/download/115/
CRA 2002 Men: Matches https://cantabsrowing.org.uk/download/115/
CRA 2004 Men: Matches https://cantabsrowing.org.uk/download/115/
Eights 1840-1976, 1995, 2009: All match https://eodg.atm.ox.ac.uk/user/dudhia/rowing/bumps
Torpids: 1859-1901, 1903-1976: All match https://eodg.atm.ox.ac.uk/user/dudhia/rowing/bumps

Here are results that I changed to reflect when divisions didn't race:

Eights 1981: First two days bottom divisions didn't race
Eights 1993: Middle two days bottom divisions didn't race
Eights 2000: First rwo days bottom divisions didn't race
Eights 2023 Men: Was missing one bump on the last day (div 6)
Lents 2001 Women: No racing on the last two days
Lents 2002 Womens: Bottom divisions missing first race
Lents 2018: No racing on middle days
Torpids 1902: No racing on one day
Torpids 1990: No racing on first rwo days
Torpids 1994: No racing on last three days
Torpids 1995: No racing on first two days
Torpids 1998: No racing on last day
Torpids 1999: Bottom divisions cancelled often
Torpids 2001: Bottom divisions didn't race first day
Torpids 2003: No racing last day
Torpids 2010: First divisions missing first races
Torpids 2018: Middle days no racing, last day partial racing

The changes above are in f0e5c905db7b6c275e68b91dbe69182582736559.
I'm happy that this update reflects our current knowledge of when divisions were cancelled, rather than when all boats in a division rowed over.
